//users
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

//authActions

//validation
export const VALIDATE_USER_IN_PROGRESS = "VALIDATE_USER_IN_PROGRESS";
export const VALIDATE_USER_SUCCESS = "VALIDATE_USER_SUCCESS";
export const VALIDATE_USER_FAILED = "VALIDATE_USER_FAILED";

//login
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//update password
export const UPDATE_PASSWORD_IN_PROGRESS = "UPDATE_PASSWORD_IN_PROGRESS";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

//forgot password
export const FORGOT_PASSWORD_IN_PROGRESS = "FORGOT_PASSWORD_IN_PROGRESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

//get notification
export const GET_NOTIFICATION_IN_PROGRESS = "GET_NOTIFICATION_IN_PROGRESS";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";

//get current user
export const GET_CURRENT_USER_DATA_IN_PROGRESS = "GET_CURRENT_USER_DATA_IN_PROGRESS";
export const GET_CURRENT_USER_DATA_SUCCESS = "GET_CURRENT_USER_DATA_SUCCESS";
export const GET_CURRENT_USER_DATA_FAILED = "GET_CURRENT_USER_DATA_FAILED";

//Edit student
export const EDIT_STUDENT_IN_PROGRESS = "EDIT_STUDENT_IN_PROGRESS";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_FAILED = "EDIT_STUDENT_FAILED";

//Update password student
export const UPDATE_STUDENT_PASSWORD_IN_PROGRESS = "UPDATE_STUDENT_PASSWORD_IN_PROGRESS";
export const UPDATE_STUDENT_PASSWORD_SUCCESS = "UPDATE_STUDENT_PASSWORD_SUCCESS";
export const UPDATE_STUDENT_PASSWORD_FAILED = "UPDATE_STUDENT_PASSWORD_FAILED";

//Update social links student
export const UPDATE_STUDENT_SOCIAL_LINKS_IN_PROGRESS = "UPDATE_STUDENT_SOCIAL_LINKS_IN_PROGRESS";
export const UPDATE_STUDENT_SOCIAL_LINKS_SUCCESS = "UPDATE_STUDENT_SOCIAL_LINKS_SUCCESS";
export const UPDATE_STUDENT_SOCIAL_LINKS_FAILED = "UPDATE_STUDENT_SOCIAL_LINKS_FAILED";

//Update cover photo student
export const UPDATE_STUDENT_COVER_PHOTO_IN_PROGRESS = "UPDATE_STUDENT_COVER_PHOTO_IN_PROGRESS";
export const UPDATE_STUDENT_COVER_PHOTO_SUCCESS = "UPDATE_STUDENT_COVER_PHOTO_SUCCESS";
export const UPDATE_STUDENT_COVER_PHOTO_FAILED = "UPDATE_STUDENT_COVER_PHOTO_FAILED";

//Update Avatar student
export const UPDATE_STUDENT_AVATAR_IN_PROGRESS = "UPDATE_STUDENT_AVATAR_IN_PROGRESS";
export const UPDATE_STUDENT_AVATAR_SUCCESS = "UPDATE_STUDENT_AVATAR_SUCCESS";
export const UPDATE_STUDENT_AVATAR_FAILED = "UPDATE_STUDENT_AVATAR_FAILED";

//Edit teacher
export const EDIT_TEACHER_IN_PROGRESS = "EDIT_TEACHER_IN_PROGRESS";
export const EDIT_TEACHER_SUCCESS = "EDIT_TEACHER_SUCCESS";
export const EDIT_TEACHER_FAILED = "EDIT_TEACHER_FAILED";

//Update password teacher
export const UPDATE_TEACHER_PASSWORD_IN_PROGRESS = "UPDATE_TEACHER_PASSWORD_IN_PROGRESS";
export const UPDATE_TEACHER_PASSWORD_SUCCESS = "UPDATE_TEACHER_PASSWORD_SUCCESS";
export const UPDATE_TEACHER_PASSWORD_FAILED = "UPDATE_TEACHER_PASSWORD_FAILED";

//Update social links teacher
export const UPDATE_TEACHER_SOCIAL_LINKS_IN_PROGRESS = "UPDATE_TEACHER_SOCIAL_LINKS_IN_PROGRESS";
export const UPDATE_TEACHER_SOCIAL_LINKS_SUCCESS = "UPDATE_TEACHER_SOCIAL_LINKS_SUCCESS";
export const UPDATE_TEACHER_SOCIAL_LINKS_FAILED = "UPDATE_TEACHER_SOCIAL_LINKS_FAILED";

//Update cover photo teacher
export const UPDATE_TEACHER_COVER_PHOTO_IN_PROGRESS = "UPDATE_TEACHER_COVER_PHOTO_IN_PROGRESS";
export const UPDATE_TEACHER_COVER_PHOTO_SUCCESS = "UPDATE_TEACHER_COVER_PHOTO_SUCCESS";
export const UPDATE_TEACHER_COVER_PHOTO_FAILED = "UPDATE_TEACHER_COVER_PHOTO_FAILED";

//Update Avatar teacher
export const UPDATE_TEACHER_AVATAR_IN_PROGRESS = "UPDATE_TEACHER_AVATAR_IN_PROGRESS";
export const UPDATE_TEACHER_AVATAR_SUCCESS = "UPDATE_TEACHER_AVATAR_SUCCESS";
export const UPDATE_TEACHER_AVATAR_FAILED = "UPDATE_TEACHER_AVATAR_FAILED";

//Get classRoom
export const GET_CLASS_ROOM_IN_PROGRESS = "GET_CLASS_ROOM_IN_PROGRESS";
export const GET_CLASS_ROOM_SUCCESS = "GET_CLASS_ROOM_SUCCESS";
export const GET_CLASS_ROOM_FAILED = "GET_CLASS_ROOM_FAILED";

// Create classrooms
export const CREATE_CLASS_ROOM_IN_PROGRESS = "CREATE_CLASS_ROOM_IN_PROGRESS";
export const CREATE_CLASS_ROOM_SUCCESS = "CREATE_CLASS_ROOM_SUCCESS";
export const CREATE_CLASS_ROOM_FAILED = "CREATE_CLASS_ROOM_FAILED";

//create student post
export const CREATE_STUDENT_POST_IN_PROGRESS = "CREATE_STUDENT_POST_IN_PROGRESS";
export const CREATE_STUDENT_POST_SUCCESS = "CREATE_STUDENT_POST_SUCCESS";
export const CREATE_STUDENT_POST_FAILED = "CREATE_STUDENT_POST_FAILED";

//admin students
export const GET_ADMIN_STUDENTS_IN_PROGRESS = "GET_ADMIN_STUDENTS_IN_PROGRESS";
export const GET_ADMIN_STUDENTS_SUCCESS = "GET_ADMIN_STUDENTS_SUCCESS";
export const GET_ADMIN_STUDENTS_FAILED = "GET_ADMIN_STUDENTS_FAILED";

//create admin students
export const CREATE_ADMIN_STUDENTS_IN_PROGRESS = "CREATE_ADMIN_STUDENTS_IN_PROGRESS";
export const CREATE_ADMIN_STUDENTS_SUCCESS = "CREATE_ADMIN_STUDENTS_SUCCESS";
export const CREATE_ADMIN_STUDENTS_FAILED = "CREATE_ADMIN_STUDENTS_FAILED";

//admin teachers
export const FETCH_ADMIN_TEACHERS_IN_PROGRESS = "FETCH_ADMIN_TEACHERS_IN_PROGRESS";
export const FETCH_ADMIN_TEACHERS_SUCCESS = "FETCH_ADMIN_TEACHERS_SUCCESS";
export const FETCH_ADMIN_TEACHERS_FAILED = "FETCH_ADMIN_TEACHERS_FAILED";

//create admin teacher
export const CREATE_ADMIN_TEACHER_IN_PROGRESS = "CREATE_ADMIN_TEACHER_IN_PROGRESS";
export const CREATE_ADMIN_TEACHER_SUCCESS = "CREATE_ADMIN_TEACHER_SUCCESS";
export const CREATE_ADMIN_TEACHER_FAILED = "CREATE_ADMIN_TEACHER_FAILED";
